### ISSUE TITLE
Color Picker - Changing one slider affects all others in Material Preview/Render view

### ISSUE THREAD

**Issue by Niruja-bit** [BlenderNPR/BEER#9] opened 2020-09-04 19:43 UTC
After updating to the current malt version today I got some weird behaviour from the color picker (see video).
In some cases changes to one slider of the color picker affect all other sliders in strange ways.

Steps to reproduce (starting from the default Blender Startup File):
* Pick malt as render engine & set color mode to standard
* Assign a malt material with a color input to an object (I tested it with the basic.glsl Shader)
* Switch from Solid to either Material Preview
* Attempt to change the color <-- weird behaviour appears
* Switch to Rendered View <-- everything is fine again

In general error always seems to appear when switching from a non-rendered mode to a rendered mode and gets resolved by switching between rendered modes.
It also doesn't appear in the non-rendered modes or when another render engine like Eevee is used.

Blender version: 2.90 Release
Malt version used: https://github.com/BlenderNPR/BEER/actions/runs/239700316

Video: https://cdn.discordapp.com/attachments/336320678498271233/751518162587222086/color_picker_error.mp4

**Comment by pragma37** [comment] 2020-09-04 20:39
I can't reproduce the issue.
The last update introduces a new dependency and installing python packages requires a Blender restart.
Could you try to restart Blender and tell me if you still have that issue.
If you do:

**For bug reports include**:
- A ***System Info* report** generated by Blender *(Help > Save System Info)*.
- A **full copy** of the ***System Console* contents** *(Window > Toggle System Console)*.
- A **.blend file** and a **list of steps** to reproduce the error.

**Comment by Niruja-bit** [comment] 2020-09-04 22:23
Restarting Blender again as an admin and dis-/enabling Malt seems to have done the trick. 
I can't reproduce the issue now.

Before the restart there were 4 add-ons with "UNKNOWN" versions (including cycles interestingly), afterwards that changed to () for all of them. Aside from that nothing changed in the System Info report.

For documentation those were the steps that got me into the weird state:
* Opened blender with admin rights
* Uninstalled the old malt version
* Installed the new version
* Enabled malt and set the shader library path
* Restarted Blender normally without admin rights (maybe that was the issue?)

This is how the list of enabled add-ons looked when things were still broken:

> io_anim_bvh (version: (1, 0, 0), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_anim_bvh\__init__.py)
> io_curve_svg (version: **UNKNOWN**, path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_curve_svg\__init__.py)
> io_mesh_ply (version: **UNKNOWN**, path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_mesh_ply\__init__.py)
> io_mesh_stl (version: (1, 1, 3), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_mesh_stl\__init__.py)
> io_mesh_uv_layout (version: (1, 1, 1), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_mesh_uv_layout\__init__.py)
> io_scene_fbx (version: (4, 21, 3), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\__init__.py)
> io_scene_gltf2 (version: (1, 3, 48), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\__init__.py)
> io_scene_obj (version: (3, 8, 0), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_obj\__init__.py)
> io_scene_x3d (version: (2, 2, 5), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_x3d\__init__.py)
> cycles (version: **UNKNOWN**, path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\cycles\__init__.py)
> add_mesh_extra_objects (version: (0, 3, 6), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\add_mesh_extra_objects\__init__.py)
> add_curve_sapling (version: (0, 3, 4), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\add_curve_sapling\__init__.py)
> io_import_images_as_planes (version: (3, 3, 1), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_import_images_as_planes.py)
> node_wrangler (version: (3, 37), path: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\node_wrangler.py)
> BlenderMalt (version: **UNKNOWN**, path: C:\Users\Niruja\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\__init__.py)

**Comment by pragma37** [comment] 2020-09-05 11:28
> Restarting Blender again as an admin and dis-/enabling Malt seems to have done the trick.
> I can't reproduce the issue now.

Great! Closing this.

**Closed by pragma37** 2020-09-05 11:28 UTC
