### ISSUE TITLE
Not Rendering (Linux, Blender 2.93.1)

### ISSUE THREAD

**Issue by adamwparker** [BlenderNPR/BEER#117] opened 2021-08-19 17:12 UTC
Default scene. Log attached.

[malt 2021-08-19(13-08).log](https://github.com/bnpr/Malt/files/7016434/malt.2021-08-19.13-08.log)

**Comment by pragma37** [comment] 2021-08-19 19:47
Thanks for the report!
This should be fixed on the latest build.

**Comment by adamwparker** [comment] 2021-08-19 21:16
I forgot to mention that this is the development build with nodes.

**Comment by pragma37** [comment] 2021-08-19 22:10
Yep, that's the one I updated.
https://github.com/bnpr/Malt/releases/tag/Development-latest
If it still doesn't work, please, post the new log from that version.

BTW, what Linux distribution do you use?
The log just says `Linux-5.11.0-7620-generic-x86_64-with-glibc2.33`.

**Comment by adamwparker** [comment] 2021-08-19 23:09
It worked for a while, then crashed. This crashing behavior also happened in the regular release when I tested it.

Pop!_OS 21.04
Gnome Version 3.38.5

[malt 2021-08-19(19-02).log](https://github.com/bnpr/Malt/files/7018104/malt.2021-08-19.19-02.log)
Thanks

**Comment by pragma37** [comment] 2021-08-25 15:09
Sorry for the late reply.

What crashes? Malt or Blender?

In your last log file, the problem seems to be a mesh that was not correctly loaded, but I'm not sure why that could happen.
Is this something you can reproduce consistently or happens randomly?

Does closing the Malt window to force a reload fixes the issue?

**Comment by adamwparker** [comment] 2021-08-25 19:18
Malt crashes

It happens through the course of normal work when I'm transforming the viewport (tumble, dolly, zoom, pan). It seems the more advanced the shader, the more it happens.

Closing the Malt window does not fix the issue. Only reverting file fixes it.

I don't know much about Glsl or programming, but maybe it's having trouble when I change the view before it finishes rendering the scene in certain cases.

**Closed as completed** 2022-03-10 17:08 UTC
