### ISSUE TITLE
All the functions in conversion.glsl are not included in the malt node panel 

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#253] opened 2022-02-19 07:06 UTC
### Malt version

Development-latest

### Blender version

Blender 3.01

### OS

Windows 10 64bits

### Hardware info

Intel i5-9400F | 8 GB RAM | NVDIA GTX 1660 Ti

### Issue description and reproduction steps

![image](https://user-images.githubusercontent.com/36077492/154790712-6f6a00bd-f6ac-40e4-ac21-461cde9d1f2c.png)

![image](https://user-images.githubusercontent.com/36077492/154790723-eaeddbd1-df1a-4e28-bf55-8b08938db447.png)

The Malt

### Attachments

As shown in the description part

**Comment by pragma37** [comment] 2022-02-20 21:31
This is not a bug.
They're now all [marked as internal](https://github.com/bnpr/Malt/blob/Development/Malt/Shaders/Node%20Utils/conversion.glsl), since the conversion is handled automatically.

**Closed as completed** 2022-02-20 21:31 UTC
