### ISSUE TITLE
Shader only seems to read a single light.

### ISSUE THREAD

**Issue by Schofje** [BlenderNPR/BEER#249] opened 2022-02-14 22:32 UTC
### Malt version

1.0 Release

### Blender version

Blender 3.0.1

### OS

Windows 10 64 Bits

### Hardware info

AMD Ryzen 2500U - AMD Vega 8 graphics - 16 GB ram

### Issue description and reproduction steps

The shader does not seem to read my second light in the scene. I get a numpy error.

Presumably the shader only loads index `0` of the light?

### Attachments

[malt 2022-02-14(22-02).log](https://github.com/bnpr/Malt/files/8064374/malt.2022-02-14.22-02.log)
[Stepped.zip](https://github.com/bnpr/Malt/files/8064388/Stepped.zip)

**Comment by pragma37** [comment] 2022-02-16 14:48
Yes, there was an issue caused by AMD expecting some data in a different format than Nvidia.
This and other AMD issues are already solved in the Development branch, but they're not in Release yet.

**Comment by pragma37** [comment] 2022-03-10 17:10
These fixes have been merged into the Release branch.

**Closed as completed by pragma37** 2022-03-10 17:10 UTC
