### ISSUE TITLE
crash when UV unwrapping after basic_normal_map.glsl applied

### ISSUE THREAD

**Issue by clacker** [BlenderNPR/BEER#16] opened 2020-11-01 22:41 UTC
Starting with the default cube selected, set the render engine to Malt and the cube's material to basic_normal_map.glsl.  Change the viewport shading to rendered.  Tab into edit mode and UV->Smart UV Project.  Blender crashes.  This doesn't happen if the Smart UV Project is done in solid viewport mode and then I switch to rendered, and it doesn't happen if I edit the UV layout in the UV editor in Malt if the UVs already exist.  It also doesn't happen if a sampler2D has already been selected.

I tried looking through the code to see where the sampler2D is added to see if there was someway to check to see if it's valid but I couldn't.

**Comment by pragma37** [comment] 2020-11-02 17:20
Looked into this and:
- This has nothing to do with the material. It happens even without a material applied.
- The crash is caused by the Nvidia driver and doesn't happen while Malt code is executing.
- The crash happens after a Vulkan call to vk_optimusGetInstanceProcAddr and Malt doesn't use Vulkan.
- The crash doesn't happen on Blender 2.91.

My take is that this is probably not directly related to Malt itself and looks like whatever it was is already fixed in master.
I'll leave the crash info here in case we still have this issue in the future.

[default_scene.crash.txt](https://github.com/BlenderNPR/BEER/files/5476787/default_scene.crash.txt)

**Comment by Arkadeievitch** [comment] 2020-11-16 20:45
Just tested my own crash with blender 2.91, and it doesn't occur, so you seem right.

**Closed** 2020-12-30 16:34 UTC
