### ISSUE TITLE
Crash when after tuing some parameters then render

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#549] opened 2024-03-23 17:47 UTC
### Malt version

node-groups-latest

### Blender version

Blender 4.0

### OS

win 11

### Hardware info

intel i5-12400F  RTX3060Ti

### Issue description and reproduction steps

change the outline width. then render, then crash.
But I cannot repeat this. The log says it is related with UI

### Attachments

[blend.zip](https://github.com/bnpr/Malt/files/14733112/blend.zip)
[log.txt](https://github.com/bnpr/Malt/files/14733113/log.txt)

**Comment by dfalt0** [comment] 2024-04-11 07:07
Hi, I'm new - take my comment with a grain of salt. I came across Malt while browsing Github; took a look at the issues for curiosity, looked at your log file - I'll try to help

The issue is coming from what you're doing in Blender, not necessarily the plugin functionality itself; my guess is how you're using it.. the TypeError "blf.size() takes exactly 2 arguments (3 given)" is repeated numerously, give me a second to think about what you're inputting that causes the plugin to then crash and complain...

At the start of log.txt, the first error states that: 

" 
Blender >   File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderMalt\MaltNodes\MaltNodeUITools.py", line 565, in context_path_ui_callback

Blender >     
Blender > blf.size(font_id, size, dpi)
Blender > 

Blender > TypeError
Blender > : 
Blender > blf.size() takes exactly 2 arguments (3 given)
"

The function blf.size() is receiving 3 things - font_id, size, and dpi - when it can only work with 2 things (the program is stating).

Can you explain a bit what you're trying to do? 
"change the outline width. then render, then crash." - what happened before that? 


---------

Not to state the obvious, but current python version is 3.12.3, you're on 3.10.13 from Sept 2023 - it's irrelevant but fyi, sometimes opensource changes based on its dependencies, it's the first thing I check when working with opensource (the dependencies, their changes, and if the project has changed based on those dependency version(s))

**Comment by HSDSZ** [comment] 2024-04-14 08:02
> Hi, I'm new - take my comment with a grain of salt. I came across Malt while browsing Github; took a look at the issues for curiosity, looked at your log file - I'll try to help
> 
> The issue is coming from what you're doing in Blender, not necessarily the plugin functionality itself; my guess is how you're using it.. the TypeError "blf.size() takes exactly 2 arguments (3 given)" is repeated numerously, give me a second to think about what you're inputting that causes the plugin to then crash and complain...
> 
> At the start of log.txt, the first error states that:
> 
> " Blender > File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderMalt\MaltNodes\MaltNodeUITools.py", line 565, in context_path_ui_callback
> 
> Blender > Blender > blf.size(font_id, size, dpi) Blender >
> 
> Blender > TypeError Blender > : Blender > blf.size() takes exactly 2 arguments (3 given) "
> 
> The function blf.size() is receiving 3 things - font_id, size, and dpi - when it can only work with 2 things (the program is stating).
> 
> Can you explain a bit what you're trying to do? "change the outline width. then render, then crash." - what happened before that?
> 
> Not to state the obvious, but current python version is 3.12.3, you're on 3.10.13 from Sept 2023 - it's irrelevant but fyi, sometimes opensource changes based on its dependencies, it's the first thing I check when working with opensource (the dependencies, their changes, and if the project has changed based on those dependency version(s))

I checked the latest release note.  It contains a bug fix related with blf size. I think this might have been fixed.

**Comment by pragma37** [comment] 2024-05-01 14:18
The bug with blf.size was indeed fixed, but I doubt that's what caused the crash.
I'm closing the issue anyway since it's not reproducible.

**Closed as not planned** 2024-05-01 14:20 UTC
