### ISSUE TITLE
Malt Subprocess forcibly closes on latest AMD Drivers

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#393] opened 2022-09-12 09:08 UTC
### Malt version

Node-UX

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Like said, the process itself will not start properly on the latest AMD Software. Adrenalin 22.8.2. Display driver version is: 08/19/2022, 31.0.12019.9007

After doing various things in Blender, (such as typing, opening preferences, searching) Blender will hang and the process will attempt to start up again, but immediately close after a split second.

Oldest driver version I have that works (reverting to this version fixes the issue) is Adrenalin 22.6.1. The display driver version specifically is: 06/22/2022, 30.0.21023.1015.

### Attachments

[malt 2022-09-12(04-06).log](https://github.com/bnpr/Malt/files/9546516/malt.2022-09-12.04-06.log)

**Comment by pragma37** [comment] 2022-09-13 20:20
Does it happen with the Malt Release version as well?

**Comment by pragma37** [comment] 2022-09-13 21:16
Never mind, after further inspection, I think this should be harmless.  
I just added code to ignore the exception, since this shouldn't actually affect the correct behavior of Malt.

I've updated the Development and node-ux branches.  
If everything works fine we can close this.

**Comment by dibli-goost** [comment] 2022-09-14 10:46
Process isn't forcibly closing anymore, but now parameters for nodes are not displaying, nothing is rendered in the viewport, and graph types are labeled red (with no options listed when selecting them. On the development branch, node parameters are displaying, but the same issues persist elsewhere regardless.

~~Not sure if it's related to the same issue~~ Edit: Definitely related. checked on previous driver version, works fine there. No issues. 

Here's the log: 
[malt 2022-09-14(05-40).log](https://github.com/bnpr/Malt/files/9565606/malt.2022-09-14.05-40.log)

**Comment by pragma37** [comment] 2022-09-14 14:27
If you go to your temp folder and delete the contents from MALT_SHADERS_CACHE (you can paste `%tmp%/MALT_SHADERS_CACHE` on the file explorer), does it work?

It's failing when it tries to load an already compiled shader. 
If that's the issue, then it's easy to fix, but I'd like to be sure first.

**Comment by dibli-goost** [comment] 2022-09-14 16:28
Alright that fixed the issues in the node editor, but the viewport display is still black, nothing rendered to the screen.

Log file doesn't really seem to show much of anything happening either?
[malt 2022-09-14(11-14).log](https://github.com/bnpr/Malt/files/9568125/malt.2022-09-14.11-14.log)

Occurring on both Development and Node UX still.

**Comment by pragma37** [comment] 2022-09-14 16:48
🤔

Does the System Console from Blender print anything?
If you simply plug a texture into the Render nodes output, is it still black?
Like this:
![imagen](https://user-images.githubusercontent.com/36610999/190214472-8d58cf1e-430e-424a-a03a-1b9861de0d39.png)

**Comment by dibli-goost** [comment] 2022-09-14 16:59
> Does the System Console from Blender print anything?

It spams the console when I unlink the color input on the render output node with this: 

```
Python: Traceback (most recent call last):
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderMalt\MaltNodes\MaltSocket.py", line 147, in draw
    node.draw_socket(context, layout, self, text)
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderMalt\MaltNodes\MaltNode.py", line 313, in draw_socket
    draw_parameter = socket.is_output == False and socket.get_linked() is None and socket.default_initialization == ''
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderMalt\MaltNodes\MaltSocket.py", line 124, in get_linked
    return get_linked_internal(self)
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderMalt\MaltNodes\MaltSocket.py", line 113, in get_linked_internal
    link = socket.links[0]
IndexError: tuple index out of range
```
But otherwise, no. Nothing.

> If you simply plug a texture into the Render nodes output, is it still black?

Does seem to be working like it should yeah
![image](https://user-images.githubusercontent.com/31767887/190216868-fa4a2ad6-b174-463c-8282-4291b14da711.png)

**Comment by pragma37** [comment] 2022-09-14 17:14
> It spams the console when I unlink the color input on the render output node with this:

Oops! I fixed that issue in the node groups branch, but not on the others.
I'm going to add that and the fix for the previous error.

For this last error, I don't know what could be going on.
I'll try to update the driver in my AMD laptop, cross my fingers and hope I can reproduce it.

**Comment by pragma37** [comment] 2022-09-18 14:22
The driver error seems to be caused by using bindless textures, which is required for using an unlimited number of textures in a material.
I found that using bindless textures only for image textures (ie. not internal Malt textures or custom inputs) seems to solve the issue.

The 22.8.2 driver version is marked as (optional), which I guess is their "nice" way of saying unstable?
I'll try to report the issue and if it doesn't get solved we'll have to use the workaround I previously mentioned.

For now, I would simply use the (recommended) driver version.

**Comment by pragma37** [comment] 2022-12-08 15:31
I'm closing this, since it has several reports that are already fixed and we have a specific thread for the one that is not fixed yet.

**Closed as completed by pragma37** 2022-12-08 15:31 UTC
