### ISSUE TITLE
Blend File cannot open after saving. A very simple reproduction file, line width not related.

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#576] opened 2024-08-22 17:54 UTC
### Malt version

node-groups-latest

### Blender version

blender 4.2

### OS

win 11

### Hardware info

intel i5-12400F  RTX3060Ti

### Issue description and reproduction steps

I finally found a possibility with the crash and file not open bug [this](https://github.com/bnpr/Malt/issues/560), and [this](https://github.com/bnpr/Malt/issues/572).

Here is how to reproduce the crash. Only one step
change the node tree from
![image](https://github.com/user-attachments/assets/a09d5c17-473c-485a-84f7-b33a6fc91fdc)
to 
![image](https://github.com/user-attachments/assets/d99b25b8-d59a-4f60-bdb8-f91e0ad5099c)

then, this blend file leave you forever.

### Attachments

[bug.zip](https://github.com/user-attachments/files/16715650/bug.zip)

**Comment by HSDSZ** [comment] 2024-08-22 17:56
I personally will not use the combined Vec4 math in the future. I will use the individual one instead

**Comment by pragma37** [comment] 2024-08-26 13:55
Is this something you can reproduce consistently?
I gave it a few tries, and even tried with a portable Blender installation and the BlenderMalt build from Github, but I still can't repro it. :(

**Comment by HSDSZ** [comment] 2024-08-26 14:34
> Is this something you can reproduce consistently? I gave it a few tries, and even tried with a portable Blender installation and the BlenderMalt build from Github, but I still can't repro it. :(

Strange. I cannot reproduce the bug too. I am sure I can reproduce the bug every time I switch to combined Vec4 when I open this issue.

**Comment by pragma37** [comment] 2024-08-26 15:51
Ah... too bad. Having a consistent way of reproducing the corruption would be massively useful.
I'm closing this as a duplicate of #560. 

> I personally will not use the combined Vec4 math in the future. I will use the individual one instead

Note that this is very unlikely to be related to any specific node, all Malt properties follow the same code path.

**Closed as not planned** 2024-08-26 15:57 UTC
