### ISSUE TITLE
Blend file can not be opened, malt related.

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#566] opened 2024-06-25 18:03 UTC
### Malt version

node-groups-latest

### Blender version

Blender 4.1.1

### OS

win 11

### Hardware info

intel i5-12400F  RTX3060Ti

### Issue description and reproduction steps

I am not sure what I have done to casue this. After rendering some images with malt, a blend file is no longer openable.
here is a screenshot of terminal when I open the blend file

![image](https://github.com/bnpr/Malt/assets/36077492/a1e471b7-6a5e-4463-8a2d-2c3fb2cc034e)

### Attachments

[Rei_treeLeavesGN_samples.zip](https://github.com/user-attachments/files/15975793/Rei_treeLeavesGN_samples.zip)

here is the blend file. although not all linked file are included. But i think blend file should be openable even without enough linked file

**Comment by HSDSZ** [comment] 2024-06-25 18:04
[Rei_treeLeavesGN_samples.crash.txt](https://github.com/user-attachments/files/15975803/Rei_treeLeavesGN_samples.crash.txt)

**Comment by pragma37** [comment] 2024-06-29 14:17
Closing as duplicate of #560

**Closed as not planned by pragma37** 2024-06-29 14:17 UTC
