### ISSUE TITLE
NoneType issues in MaltFunctionNode

### ISSUE THREAD

**Issue by ParaKrei** [BlenderNPR/BEER#575] opened 2024-08-19 05:36 UTC
### Malt version

Release

### Blender version

4.2 (Steam)

### OS

Fedora Linux 40 (64-bit; X11 MATE)

### Hardware info

AMD Ryzen 5 7600 | 16GB RAM | AMD Radeon RX 6600

### Issue description and reproduction steps

In any files I made with previous versions of Malt, and in even default scenes, Malt will no longer render, only showing complete darkness in viewport and render.
After testing both the current release and development versions, I cloned the dev branch onto my system to read any errors and came across a traceback for a NoneType object, which pointed to MaltFunctionNode's "get_function" function.
Unfortunately the session log hasn't caught anything, and I was only able to get this error by launching Blender in my terminal.

### Attachments

Here's the log straight from my terminal (traceback starts at line 104).
[blender.log](https://github.com/user-attachments/files/16656181/blender.log)

**Comment by pragma37** [comment] 2024-08-26 14:11
It might be related to #568.

Do older versions still work for you?
For example, if you download Blender 4.0 and install https://github.com/bnpr/Malt/releases/tag/blender-4.0-last-version, does it work?

**Comment by ParaKrei** [comment] 2024-08-29 18:37
Sorry that it took a while for me to reply, I didn't see your comment until today... anyways, I just tested a clean Blender 4.0 copy (in portable mode) with Malt's last 4.0 version, and the same issue is still present, even down to the error.

**Comment by pragma37** [comment] 2024-09-14 16:43
I'm closing this issue as a duplicate of #568 then, since this is likely the same driver problem.
Please, follow that issue from now on.

**Closed as not planned by pragma37** 2024-09-14 16:43 UTC
